[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turbo-tosec"
version = "2.6.5"  # Starter version
description = "High-performance TOSEC DAT importer using DuckDB"
authors = [
  { name="Berk Acunas", email="berkacunas@gmail.com" },
]
dependencies = [
    "duckdb",
    "tqdm",
    "pyarrow>=14.0.0",
    "psutil"
]
requires-python = ">=3.10"

[project.scripts]
turbo-tosec = "turbo_tosec.cli:main"

[tool.setuptools.packages.find]
where = ["src"] 
include = ["turbo_tosec*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.mypy]
python_version = "2.6.5"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true  # Requires all functions to have type hints
ignore_missing_imports = true # Silences errors for libraries without type hints